-- Assignee (CONTEXT.md; D3 S2). In M2 the only assignable Assignee is
-- the Owner, a human.
--
-- A nullable TEXT discriminator, like goal/context (000005/000006):
-- NULL means "never assigned", surfaced as "" on the wire. A later
-- milestone can add an Agent kind -- a new value plus its own
-- reference column -- as a purely additive migration.
--
-- No CHECK, matching status/template/completion_condition: Galley is
-- the only writer (ADR 0001) and enforces the value set itself.
--
-- No backfill: the Assignee concept did not exist before this
-- migration, so every pre-existing Ticket was genuinely unassigned.
ALTER TABLE tickets ADD COLUMN assignee_type TEXT;
