//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentKind.
const (
	AgentKindCoding   AgentKind = "coding"
	AgentKindResearch AgentKind = "research"
)

// Valid indicates whether the value is a known member of the AgentKind enum.
func (e AgentKind) Valid() bool {
	switch e {
	case AgentKindCoding:
		return true
	case AgentKindResearch:
		return true
	default:
		return false
	}
}

// Defines values for AgentReadinessInput.
const (
	AgentReadinessInputGoal            AgentReadinessInput = "goal"
	AgentReadinessInputRepository      AgentReadinessInput = "repository"
	AgentReadinessInputSuccessCriteria AgentReadinessInput = "successCriteria"
)

// Valid indicates whether the value is a known member of the AgentReadinessInput enum.
func (e AgentReadinessInput) Valid() bool {
	switch e {
	case AgentReadinessInputGoal:
		return true
	case AgentReadinessInputRepository:
		return true
	case AgentReadinessInputSuccessCriteria:
		return true
	default:
		return false
	}
}

// Defines values for AssignTicketRequestType.
const (
	AssignTicketRequestTypeAgent AssignTicketRequestType = "agent"
	AssignTicketRequestTypeOwner AssignTicketRequestType = "owner"
)

// Valid indicates whether the value is a known member of the AssignTicketRequestType enum.
func (e AssignTicketRequestType) Valid() bool {
	switch e {
	case AssignTicketRequestTypeAgent:
		return true
	case AssignTicketRequestTypeOwner:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStatusStatus.
const (
	DatabaseStatusStatusError DatabaseStatusStatus = "error"
	DatabaseStatusStatusOk    DatabaseStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the DatabaseStatusStatus enum.
func (e DatabaseStatusStatus) Valid() bool {
	switch e {
	case DatabaseStatusStatusError:
		return true
	case DatabaseStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for OpenRoundState.
const (
	OpenRoundClaimed OpenRoundState = "claimed"
	OpenRoundRunning OpenRoundState = "running"
)

// Valid indicates whether the value is a known member of the OpenRoundState enum.
func (e OpenRoundState) Valid() bool {
	switch e {
	case OpenRoundClaimed:
		return true
	case OpenRoundRunning:
		return true
	default:
		return false
	}
}

// Defines values for RoundEventType.
const (
	RoundEventDelivered        RoundEventType = "delivered"
	RoundEventExecutionStarted RoundEventType = "execution_started"
	RoundEventProgress         RoundEventType = "progress"
	RoundEventUsageObserved    RoundEventType = "usage_observed"
)

// Valid indicates whether the value is a known member of the RoundEventType enum.
func (e RoundEventType) Valid() bool {
	switch e {
	case RoundEventDelivered:
		return true
	case RoundEventExecutionStarted:
		return true
	case RoundEventProgress:
		return true
	case RoundEventUsageObserved:
		return true
	default:
		return false
	}
}

// Defines values for RoundState.
const (
	RoundClaimed   RoundState = "claimed"
	RoundDelivered RoundState = "delivered"
	RoundRunning   RoundState = "running"
)

// Valid indicates whether the value is a known member of the RoundState enum.
func (e RoundState) Valid() bool {
	switch e {
	case RoundClaimed:
		return true
	case RoundDelivered:
		return true
	case RoundRunning:
		return true
	default:
		return false
	}
}

// Defines values for RunnerCommandAckOutcome.
const (
	RunnerCommandApplied RunnerCommandAckOutcome = "applied"
	RunnerCommandIgnored RunnerCommandAckOutcome = "ignored"
)

// Valid indicates whether the value is a known member of the RunnerCommandAckOutcome enum.
func (e RunnerCommandAckOutcome) Valid() bool {
	switch e {
	case RunnerCommandApplied:
		return true
	case RunnerCommandIgnored:
		return true
	default:
		return false
	}
}

// Defines values for RunnerCommandType.
const (
	RunnerCommandStop RunnerCommandType = "stop"
)

// Valid indicates whether the value is a known member of the RunnerCommandType enum.
func (e RunnerCommandType) Valid() bool {
	switch e {
	case RunnerCommandStop:
		return true
	default:
		return false
	}
}

// Defines values for RunnerHealthState.
const (
	RunnerConnected    RunnerHealthState = "connected"
	RunnerDisconnected RunnerHealthState = "disconnected"
	RunnerNotPaired    RunnerHealthState = "not_paired"
)

// Valid indicates whether the value is a known member of the RunnerHealthState enum.
func (e RunnerHealthState) Valid() bool {
	switch e {
	case RunnerConnected:
		return true
	case RunnerDisconnected:
		return true
	case RunnerNotPaired:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseApplication.
const (
	Galley StatusResponseApplication = "galley"
)

// Valid indicates whether the value is a known member of the StatusResponseApplication enum.
func (e StatusResponseApplication) Valid() bool {
	switch e {
	case Galley:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseEnvironment.
const (
	Development StatusResponseEnvironment = "development"
	Production  StatusResponseEnvironment = "production"
)

// Valid indicates whether the value is a known member of the StatusResponseEnvironment enum.
func (e StatusResponseEnvironment) Valid() bool {
	switch e {
	case Development:
		return true
	case Production:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusOk StatusResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case StatusResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for TicketAssigneeType.
const (
	TicketAssigneeTypeAgent TicketAssigneeType = "agent"
	TicketAssigneeTypeEmpty TicketAssigneeType = ""
	TicketAssigneeTypeOwner TicketAssigneeType = "owner"
)

// Valid indicates whether the value is a known member of the TicketAssigneeType enum.
func (e TicketAssigneeType) Valid() bool {
	switch e {
	case TicketAssigneeTypeAgent:
		return true
	case TicketAssigneeTypeEmpty:
		return true
	case TicketAssigneeTypeOwner:
		return true
	default:
		return false
	}
}

// Defines values for TicketCompletionCondition.
const (
	HumanAcceptance TicketCompletionCondition = "humanAcceptance"
	ReviewedPrMerge TicketCompletionCondition = "reviewedPrMerge"
)

// Valid indicates whether the value is a known member of the TicketCompletionCondition enum.
func (e TicketCompletionCondition) Valid() bool {
	switch e {
	case HumanAcceptance:
		return true
	case ReviewedPrMerge:
		return true
	default:
		return false
	}
}

// Defines values for TicketStatus.
const (
	Backlog    TicketStatus = "Backlog"
	Blocked    TicketStatus = "Blocked"
	Done       TicketStatus = "Done"
	InProgress TicketStatus = "InProgress"
	InReview   TicketStatus = "InReview"
	Ready      TicketStatus = "Ready"
)

// Valid indicates whether the value is a known member of the TicketStatus enum.
func (e TicketStatus) Valid() bool {
	switch e {
	case Backlog:
		return true
	case Blocked:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case InReview:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for TicketTemplate.
const (
	Basic  TicketTemplate = "Basic"
	Coding TicketTemplate = "Coding"
)

// Valid indicates whether the value is a known member of the TicketTemplate enum.
func (e TicketTemplate) Valid() bool {
	switch e {
	case Basic:
		return true
	case Coding:
		return true
	default:
		return false
	}
}

// Defines values for UsageObservedDataBasis.
const (
	UsageBasisEstimated UsageObservedDataBasis = "estimated"
	UsageBasisReported  UsageObservedDataBasis = "reported"
)

// Valid indicates whether the value is a known member of the UsageObservedDataBasis enum.
func (e UsageObservedDataBasis) Valid() bool {
	switch e {
	case UsageBasisEstimated:
		return true
	case UsageBasisReported:
		return true
	default:
		return false
	}
}

// AcknowledgeRoundCommandRequest defines model for AcknowledgeRoundCommandRequest.
type AcknowledgeRoundCommandRequest struct {
	Outcome RunnerCommandAckOutcome `json:"outcome"`
}

// AdvanceDevClockRequest defines model for AdvanceDevClockRequest.
type AdvanceDevClockRequest struct {
	Seconds int `json:"seconds"`
}

// Agent defines model for Agent.
type Agent struct {
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`

	// Kind Set at creation and never changed in M4.
	Kind AgentKind `json:"kind"`
	Name string    `json:"name"`
}

// AgentKind Set at creation and never changed in M4.
type AgentKind string

// AgentList defines model for AgentList.
type AgentList struct {
	Agents []Agent `json:"agents"`
}

// AgentReadinessInput A Ticket field an Agent-assigned Ticket needs before Ready (D3 S1): `goal` and `successCriteria` always, `repository` for a `coding` Agent.
type AgentReadinessInput string

// AssignTicketRequest `agentId` is required when `type` is `agent` and rejected otherwise.
type AssignTicketRequest struct {
	AgentId *string                 `json:"agentId,omitempty"`
	Type    AssignTicketRequestType `json:"type"`
}

// AssignTicketRequestType defines model for AssignTicketRequest.Type.
type AssignTicketRequestType string

// Badge defines model for Badge.
type Badge struct {
	CreatedAt string `json:"createdAt"`
	Id        string `json:"id"`
	Name      string `json:"name"`
}

// BadgeList defines model for BadgeList.
type BadgeList struct {
	Badges []Badge `json:"badges"`
}

// ChangeTicketStatusRequest `status` names the requested target Status, validated against the Ticket's persisted current Status per D3 S2. `Done` is always rejected here -- see `POST /api/tickets/{id}/accept`.
type ChangeTicketStatusRequest struct {
	// Status A Ticket's lifecycle stage (CONTEXT.md, "Status"). Moves between these values are validated against the persisted current Status per D3 S2 (docs/decisions/d3-agent-template-compatibility.md). `Done` is reachable only through explicit Accept.
	Status TicketStatus `json:"status"`
}

// ClaimedTicket defines model for ClaimedTicket.
type ClaimedTicket struct {
	Constraints     string `json:"constraints"`
	Context         string `json:"context"`
	Goal            string `json:"goal"`
	Id              string `json:"id"`
	Repository      string `json:"repository"`
	SuccessCriteria string `json:"successCriteria"`
	Title           string `json:"title"`
}

// CreateAgentRequest defines model for CreateAgentRequest.
type CreateAgentRequest struct {
	// Kind Set at creation and never changed in M4.
	Kind AgentKind `json:"kind"`
	Name string    `json:"name"`
}

// CreateBadgeRequest defines model for CreateBadgeRequest.
type CreateBadgeRequest struct {
	Name string `json:"name"`
}

// CreateDiagnosticNoteRequest defines model for CreateDiagnosticNoteRequest.
type CreateDiagnosticNoteRequest struct {
	Note string `json:"note"`
}

// CreateTicketRequest defines model for CreateTicketRequest.
type CreateTicketRequest struct {
	// Constraints Same as `goal`.
	Constraints *string `json:"constraints,omitempty"`

	// Context Same as `goal`.
	Context *string `json:"context,omitempty"`

	// Goal Same trimming and limit as `UpdateTicketRequest.goal`; omitted or empty leaves it unset.
	Goal *string `json:"goal,omitempty"`

	// Repository Same as `goal`.
	Repository *string `json:"repository,omitempty"`

	// SuccessCriteria Same as `goal`.
	SuccessCriteria *string `json:"successCriteria,omitempty"`

	// Template A Ticket's built-in Template (issue #59), chosen at capture (default Basic). Under the accepted D3 decision (docs/decisions/d3-agent-template-compatibility.md), a Template supplies presentation, required information, and a *default* completion condition only -- it never restricts which Agent or execution engine may be assigned (docs/ticket-creation.md, "Flexible ticket structure"). Changing a Ticket's Template after creation is out of scope for M2: post-delivery Template/repository change is D4, owned by M8.
	Template *TicketTemplate `json:"template,omitempty"`

	// Title Trimmed of leading/trailing whitespace before validation. Must be non-empty and at most 200 characters after trimming.
	Title string `json:"title"`
}

// DatabaseStatus Added by issue #52. Reachability and applied migration version, checked live on every request -- never cached from process start, and never reported as "ok" when the database is unreachable.
type DatabaseStatus struct {
	// Error Present only when status is "error". A short, fixed, non-secret explanation -- never the underlying driver error text or any part of the connection string.
	Error *string `json:"error,omitempty"`

	// MigrationVersion The most recently applied forward-only migration version (see apps/galley/internal/migrations), or null if it could not be determined -- either because the database is unreachable (status "error") or because no migration has been applied yet on an otherwise-reachable database (status "ok").
	MigrationVersion *int                 `json:"migrationVersion"`
	Status           DatabaseStatusStatus `json:"status"`
}

// DatabaseStatusStatus defines model for DatabaseStatus.Status.
type DatabaseStatusStatus string

// DeliveredData Each value is not blank and has no control characters but tab and line feed.
type DeliveredData struct {
	// BodyMarkdown The result, at most 1 MiB (1048576 bytes) as UTF-8.
	BodyMarkdown string `json:"bodyMarkdown"`

	// CriteriaAssessment The Success Criteria assessment, counted in Unicode code points.
	CriteriaAssessment string `json:"criteriaAssessment"`

	// Summary The change summary, counted in Unicode code points.
	Summary string `json:"summary"`
}

// DevClock defines model for DevClock.
type DevClock struct {
	Now time.Time `json:"now"`
}

// DiagnosticNote Development-only diagnostic record (issue #52), persisted in the diagnostic_notes table. Not a domain/ticket concept.
type DiagnosticNote struct {
	// CreatedAt RFC3339 UTC timestamp of when the note was persisted.
	CreatedAt string `json:"createdAt"`
	Id        int    `json:"id"`
	Note      string `json:"note"`
}

// DiagnosticNoteList defines model for DiagnosticNoteList.
type DiagnosticNoteList struct {
	Notes []DiagnosticNote `json:"notes"`
}

// ErrorBody The shared JSON error shape used by every Galley error response.
type ErrorBody struct {
	Error ErrorDetail `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Short, stable, snake_case identifier (e.g. "not_found").
	Code string `json:"code"`

	// Message Human-readable, non-secret explanation.
	Message string `json:"message"`

	// Missing Present only with `agent_readiness_incomplete`.
	Missing *[]AgentReadinessInput `json:"missing,omitempty"`

	// RoundId Present only with `round_open`; the Ticket's open Round.
	RoundId *string `json:"roundId,omitempty"`
}

// ExecutionStartedData defines model for ExecutionStartedData.
type ExecutionStartedData struct {
	// EngineReference Attached as the Round's current engine execution reference.
	EngineReference string `json:"engineReference"`
}

// OpenRoundState A claimed Round leaves the Ticket Ready; a running one has moved it to In Progress.
type OpenRoundState string

// Owner ticketIt's stable internal Owner identity -- independent of any GitHub identifier (docs/deployment.md, "Ownership and sign-in"). `login` is the linked GitHub identity's most recently observed login, shown for display only: matching a sign-in to this Owner always uses the immutable provider account id, never this field.
type Owner struct {
	// Id ticketIt's own Owner id -- not a GitHub identifier.
	Id int `json:"id"`

	// Login The linked GitHub account's current login, for display only.
	Login string `json:"login"`
}

// ProgressData defines model for ProgressData.
type ProgressData struct {
	// Note Counted in Unicode code points. Not blank; no control characters but tab and line feed.
	Note string `json:"note"`
}

// RegisterRunnerRequest defines model for RegisterRunnerRequest.
type RegisterRunnerRequest struct {
	Hostname        string `json:"hostname"`
	MichelinVersion string `json:"michelinVersion"`
}

// RenameAgentRequest defines model for RenameAgentRequest.
type RenameAgentRequest struct {
	Name string `json:"name"`
}

// ReorderTicketRequest Exactly one of `before` or `after`.
type ReorderTicketRequest struct {
	After  *string `json:"after,omitempty"`
	Before *string `json:"before,omitempty"`
}

// RoundActivityNote defines model for RoundActivityNote.
type RoundActivityNote struct {
	Note string `json:"note"`

	// OccurredAt The runner's clock.
	OccurredAt time.Time `json:"occurredAt"`

	// Seq Galley's arrival order within the Round, without gaps.
	Seq int `json:"seq"`
}

// RoundCommandAcknowledgement defines model for RoundCommandAcknowledgement.
type RoundCommandAcknowledgement struct {
	AcknowledgedAt time.Time               `json:"acknowledgedAt"`
	Id             string                  `json:"id"`
	Outcome        RunnerCommandAckOutcome `json:"outcome"`
}

// RoundDeliverable defines model for RoundDeliverable.
type RoundDeliverable struct {
	BodyMarkdown       string `json:"bodyMarkdown"`
	CriteriaAssessment string `json:"criteriaAssessment"`
	Summary            string `json:"summary"`
}

// RoundEventRequest defines model for RoundEventRequest.
type RoundEventRequest struct {
	// ClaimEpoch The fencing token from the claim.
	ClaimEpoch int `json:"claimEpoch"`

	// Data The payload for `type`: `ExecutionStartedData`, `ProgressData`, `UsageObservedData` or `DeliveredData`.
	Data RoundEventRequest_Data `json:"data"`

	// IdempotencyKey Taken verbatim; identity is never trimmed.
	IdempotencyKey string `json:"idempotencyKey"`

	// OccurredAt The runner's clock; Galley keeps it and times the Round by its own.
	OccurredAt string `json:"occurredAt"`

	// Type Grows by slice.
	Type RoundEventType `json:"type"`
}

// RoundEventRequest_Data The payload for `type`: `ExecutionStartedData`, `ProgressData`, `UsageObservedData` or `DeliveredData`.
type RoundEventRequest_Data struct {
	union json.RawMessage
}

// RoundEventResult defines model for RoundEventResult.
type RoundEventResult struct {
	// EndedAt For `delivered`.
	EndedAt *time.Time `json:"endedAt,omitempty"`

	// ObservationId For `usage_observed`, the observation recorded.
	ObservationId *string `json:"observationId,omitempty"`
	RoundId       string  `json:"roundId"`

	// Seq For `progress`, the note's place in the Round's activity.
	Seq       *int      `json:"seq,omitempty"`
	StartedAt time.Time `json:"startedAt"`

	// State `claimed` and `running` are open. `delivered` has ended and moved the Ticket to In Review.
	State RoundState `json:"state"`

	// Type Grows by slice.
	Type RoundEventType `json:"type"`
}

// RoundEventType Grows by slice.
type RoundEventType string

// RoundState `claimed` and `running` are open. `delivered` has ended and moved the Ticket to In Review.
type RoundState string

// RoundUsage Sums of the known values. Unknown is never counted as zero.
type RoundUsage struct {
	// ActiveMs `complete` and `estimated` mean for this figure what they mean for the cost in `RoundUsage`.
	ActiveMs UsageCount `json:"activeMs"`

	// Complete At least one observation, and every observation has a known cost.
	Complete bool `json:"complete"`

	// CostUsd Null when no observation has a known cost.
	CostUsd *string `json:"costUsd"`

	// Estimated An observation with a known cost is `estimated`.
	Estimated bool `json:"estimated"`

	// InputTokens `complete` and `estimated` mean for this figure what they mean for the cost in `RoundUsage`.
	InputTokens  UsageCount `json:"inputTokens"`
	Observations int        `json:"observations"`

	// OutputTokens `complete` and `estimated` mean for this figure what they mean for the cost in `RoundUsage`.
	OutputTokens UsageCount `json:"outputTokens"`
}

// RunnerClaim defines model for RunnerClaim.
type RunnerClaim struct {
	Agent TicketAssigneeAgent `json:"agent"`

	// ClaimEpoch Fencing token; events must carry it with `roundId`. A Ticket's Rounds get increasing epochs.
	ClaimEpoch int           `json:"claimEpoch"`
	RoundId    string        `json:"roundId"`
	Sequence   int           `json:"sequence"`
	Ticket     ClaimedTicket `json:"ticket"`
}

// RunnerCommand defines model for RunnerCommand.
type RunnerCommand struct {
	// ClaimEpoch The claim epoch the command targets. A runner holding another epoch acknowledges it `ignored` and does not act on it.
	ClaimEpoch int `json:"claimEpoch"`

	// Id The command's idempotency key.
	Id       string    `json:"id"`
	IssuedAt time.Time `json:"issuedAt"`

	// Type Grows by slice.
	Type RunnerCommandType `json:"type"`
}

// RunnerCommandAckOutcome defines model for RunnerCommandAckOutcome.
type RunnerCommandAckOutcome string

// RunnerCommandList defines model for RunnerCommandList.
type RunnerCommandList struct {
	Commands []RunnerCommand `json:"commands"`
}

// RunnerCommandType Grows by slice.
type RunnerCommandType string

// RunnerHealth defines model for RunnerHealth.
type RunnerHealth struct {
	// CheckedAt Galley's clock when `state` was derived.
	CheckedAt       time.Time         `json:"checkedAt"`
	Hostname        *string           `json:"hostname"`
	LastSeenAt      *time.Time        `json:"lastSeenAt"`
	MichelinVersion *string           `json:"michelinVersion"`
	PairedAt        *time.Time        `json:"pairedAt"`
	RegisteredAt    *time.Time        `json:"registeredAt"`
	State           RunnerHealthState `json:"state"`
}

// RunnerHealthState defines model for RunnerHealthState.
type RunnerHealthState string

// RunnerHeartbeat defines model for RunnerHeartbeat.
type RunnerHeartbeat struct {
	LastSeenAt time.Time `json:"lastSeenAt"`
}

// RunnerPairing defines model for RunnerPairing.
type RunnerPairing struct {
	Health RunnerHealth `json:"health"`
	Token  string       `json:"token"`
}

// RunnerRegistration defines model for RunnerRegistration.
type RunnerRegistration struct {
	RegisteredAt time.Time `json:"registeredAt"`
}

// SessionResponse defines model for SessionResponse.
type SessionResponse struct {
	// Owner ticketIt's stable internal Owner identity -- independent of any GitHub identifier (docs/deployment.md, "Ownership and sign-in"). `login` is the linked GitHub identity's most recently observed login, shown for display only: matching a sign-in to this Owner always uses the immutable provider account id, never this field.
	Owner Owner `json:"owner"`
}

// StatusResponse The fixed GET /api/status payload.
type StatusResponse struct {
	Application StatusResponseApplication `json:"application"`

	// Database Added by issue #52. Reachability and applied migration version, checked live on every request -- never cached from process start, and never reported as "ok" when the database is unreachable.
	Database    DatabaseStatus            `json:"database"`
	Environment StatusResponseEnvironment `json:"environment"`

	// StartedAt RFC3339 UTC timestamp, captured once at process start.
	StartedAt string               `json:"startedAt"`
	Status    StatusResponseStatus `json:"status"`

	// Version Galley's configured version string (GALLEY_VERSION).
	Version string `json:"version"`
}

// StatusResponseApplication defines model for StatusResponse.Application.
type StatusResponseApplication string

// StatusResponseEnvironment defines model for StatusResponse.Environment.
type StatusResponseEnvironment string

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// Ticket ticketIt's first domain record (issue #56): a title captured in Backlog. No work-type/category column -- see docs/ticket-creation.md, "Flexible ticket structure". Owned by exactly one Owner, enforced by Galley (docs/adr/0001-single-authority-galley.md). Addressed by an opaque, non-sequential public identifier (issue #57) -- see `id` below.
type Ticket struct {
	AllowedActions TicketAllowedActions `json:"allowedActions"`

	// ArchivedAt Null for an active Ticket; RFC3339 UTC archive timestamp otherwise. Status is retained separately.
	ArchivedAt *time.Time `json:"archivedAt"`

	// AssigneeAgent Null unless `assigneeType` is `agent`.
	AssigneeAgent *TicketAssigneeAgent `json:"assigneeAgent"`

	// AssigneeType The kind of Assignee responsible for a Ticket (CONTEXT.md, "Assignee"). "" means unassigned, always present on the wire, matching `goal`'s convention.
	AssigneeType TicketAssigneeType `json:"assigneeType"`

	// Badges Ordered by case-insensitive name ascending, then id ascending. Empty when none attached.
	Badges []TicketBadge `json:"badges"`

	// CompletionCondition The condition that completes a Ticket (CONTEXT.md, "Done"): human acceptance, or merging its reviewed pull request. Derived from the Ticket's Template default exactly once, at creation (issue #59, D3) -- there is no request field or operation anywhere in this contract that sets or changes it directly. Assignment, reassignment, and editing any other field never change it.
	CompletionCondition TicketCompletionCondition `json:"completionCondition"`

	// Constraints Manual refinement (issue #58 -- prompt "State what must stay unchanged or remain out of scope."). Plain text; see `goal`'s description for the "" convention.
	Constraints string `json:"constraints"`

	// Context Manual refinement (issue #58 -- prompt "Supply relevant background, links, repositories, or examples."). Plain text; see `goal`'s description for the "" convention.
	Context string `json:"context"`

	// CreatedAt RFC3339 UTC timestamp of when the Ticket was captured.
	CreatedAt string `json:"createdAt"`

	// Delivery The Ticket's latest Round, when that Round was delivered. Null before any delivery and once a later Round is claimed.
	Delivery *TicketDelivery `json:"delivery"`

	// Goal Manual refinement (issue #58, docs/ticket-creation.md, "Manual guidance" -- prompt "What outcome do you want?"). Plain text, never Markdown (M7 owns report rendering). Always present on the wire; "" means never set or cleared -- read access never distinguishes those two, only PATCH's request body does (see UpdateTicketRequest).
	Goal string `json:"goal"`

	// Id Opaque public identifier (issue #57), used in URLs and by GET /api/tickets/{id}. Non-sequential and non-guessable -- never the internal sequential database id, which no Galley endpoint exposes.
	Id string `json:"id"`

	// OpenRound Null unless the Ticket has an open Round. While it is set, every change to the Ticket's fields, Assignee, Badges, Status or position, Accept and archive is rejected with `round_open`, and `allowedActions` offers none of them.
	OpenRound *TicketOpenRound `json:"openRound"`

	// Repository One Ticket repository reference (issue #59, D3 S1 check 3), available on either Template, and required before Ready only by a `coding` Agent's readiness. There is exactly one such field on a Ticket; the Coding Template surfaces it by default, but it is not a competing Basic-only concept. Plain text (e.g. an "owner/repo" name or a URL) with no format enforced yet. Always present on the wire; "" means never set or cleared -- see `goal`'s description for the same convention.
	Repository string `json:"repository"`

	// RequestingAgentWork Unarchived, Ready, Agent-assigned, every AgentReadinessInput that Agent needs is present, and no open Round. Creates no Round by itself.
	RequestingAgentWork bool `json:"requestingAgentWork"`

	// Status A Ticket's lifecycle stage (CONTEXT.md, "Status"). Moves between these values are validated against the persisted current Status per D3 S2 (docs/decisions/d3-agent-template-compatibility.md). `Done` is reachable only through explicit Accept.
	Status TicketStatus `json:"status"`

	// SuccessCriteria Manual refinement (issue #58 -- prompt "Describe observable conditions that demonstrate the outcome was achieved."). CONTEXT.md's "Success Criteria" term -- not "acceptance criteria". Plain text; see `goal`'s description for the "" convention.
	SuccessCriteria string `json:"successCriteria"`

	// Template A Ticket's built-in Template (issue #59), chosen at capture (default Basic). Under the accepted D3 decision (docs/decisions/d3-agent-template-compatibility.md), a Template supplies presentation, required information, and a *default* completion condition only -- it never restricts which Agent or execution engine may be assigned (docs/ticket-creation.md, "Flexible ticket structure"). Changing a Ticket's Template after creation is out of scope for M2: post-delivery Template/repository change is D4, owned by M8.
	Template TicketTemplate `json:"template"`
	Title    string         `json:"title"`

	// UpdatedAt RFC3339 UTC timestamp of the Ticket's last change. Equal to createdAt until a transition (#60) or a refinement edit (#58) changes it.
	UpdatedAt string `json:"updatedAt"`
}

// TicketAllowedActions defines model for TicketAllowedActions.
type TicketAllowedActions struct {
	Accept TicketCommandAvailability `json:"accept"`
	Rework TicketCommandAvailability `json:"rework"`

	// StatusChangeRejections Targets D3 S2's table permits from the current Status that this Ticket's Agent assignment or missing inputs rule out, each with the status command's error.
	StatusChangeRejections []TicketStatusChangeRejection `json:"statusChangeRejections"`

	// StatusChanges Targets accepted by a plain status command from this Ticket's current Status.
	StatusChanges []TicketStatus `json:"statusChanges"`

	// Stop Unavailable with `stop_already_requested` once Stop is requested.
	Stop TicketCommandAvailability `json:"stop"`
}

// TicketAssigneeAgent defines model for TicketAssigneeAgent.
type TicketAssigneeAgent struct {
	Id string `json:"id"`

	// Kind Set at creation and never changed in M4.
	Kind AgentKind `json:"kind"`
	Name string    `json:"name"`
}

// TicketAssigneeType The kind of Assignee responsible for a Ticket (CONTEXT.md, "Assignee"). "" means unassigned, always present on the wire, matching `goal`'s convention.
type TicketAssigneeType string

// TicketBadge defines model for TicketBadge.
type TicketBadge struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// TicketCommandAvailability defines model for TicketCommandAvailability.
type TicketCommandAvailability struct {
	Available bool `json:"available"`

	// Reason Required when unavailable; absent when available. Matches the command's error.
	Reason *ErrorDetail `json:"reason,omitempty"`
}

// TicketCompletionCondition The condition that completes a Ticket (CONTEXT.md, "Done"): human acceptance, or merging its reviewed pull request. Derived from the Ticket's Template default exactly once, at creation (issue #59, D3) -- there is no request field or operation anywhere in this contract that sets or changes it directly. Assignment, reassignment, and editing any other field never change it.
type TicketCompletionCondition string

// TicketDelivery defines model for TicketDelivery.
type TicketDelivery struct {
	// Agent The Agent of the delivered Round.
	Agent       TicketAssigneeAgent `json:"agent"`
	DeliveredAt time.Time           `json:"deliveredAt"`
	RoundId     string              `json:"roundId"`
	Sequence    int                 `json:"sequence"`
}

// TicketList The signed-in Owner's Tickets, newest first (createdAt descending, id descending as the tiebreak).
type TicketList struct {
	Tickets []Ticket `json:"tickets"`
}

// TicketOpenRound defines model for TicketOpenRound.
type TicketOpenRound struct {
	// Agent The Agent assigned when the Round was claimed.
	Agent     TicketAssigneeAgent `json:"agent"`
	ClaimedAt time.Time           `json:"claimedAt"`
	Id        string              `json:"id"`
	Sequence  int                 `json:"sequence"`
	StartedAt *time.Time          `json:"startedAt"`

	// State A claimed Round leaves the Ticket Ready; a running one has moved it to In Progress.
	State OpenRoundState `json:"state"`

	// StopRequestedAt When the Owner requested Stop; the Ticket shows Stopping. Not a Status.
	StopRequestedAt *time.Time `json:"stopRequestedAt"`
}

// TicketRound defines model for TicketRound.
type TicketRound struct {
	// Activity The latest 50 notes, oldest first.
	Activity []RoundActivityNote `json:"activity"`

	// Agent The Agent assigned when the Round was claimed.
	Agent     TicketAssigneeAgent `json:"agent"`
	ClaimedAt time.Time           `json:"claimedAt"`

	// Deliverable Set exactly when `state` is `delivered`.
	Deliverable *RoundDeliverable `json:"deliverable"`
	EndedAt     *time.Time        `json:"endedAt"`
	Id          string            `json:"id"`
	Sequence    int               `json:"sequence"`
	StartedAt   *time.Time        `json:"startedAt"`

	// State `claimed` and `running` are open. `delivered` has ended and moved the Ticket to In Review.
	State RoundState `json:"state"`

	// Usage Sums of the known values. Unknown is never counted as zero.
	Usage RoundUsage `json:"usage"`
}

// TicketRoundList defines model for TicketRoundList.
type TicketRoundList struct {
	Rounds []TicketRound `json:"rounds"`
}

// TicketStatus A Ticket's lifecycle stage (CONTEXT.md, "Status"). Moves between these values are validated against the persisted current Status per D3 S2 (docs/decisions/d3-agent-template-compatibility.md). `Done` is reachable only through explicit Accept.
type TicketStatus string

// TicketStatusChangeRejection defines model for TicketStatusChangeRejection.
type TicketStatusChangeRejection struct {
	Reason ErrorDetail `json:"reason"`

	// Status A Ticket's lifecycle stage (CONTEXT.md, "Status"). Moves between these values are validated against the persisted current Status per D3 S2 (docs/decisions/d3-agent-template-compatibility.md). `Done` is reachable only through explicit Accept.
	Status TicketStatus `json:"status"`
}

// TicketTemplate A Ticket's built-in Template (issue #59), chosen at capture (default Basic). Under the accepted D3 decision (docs/decisions/d3-agent-template-compatibility.md), a Template supplies presentation, required information, and a *default* completion condition only -- it never restricts which Agent or execution engine may be assigned (docs/ticket-creation.md, "Flexible ticket structure"). Changing a Ticket's Template after creation is out of scope for M2: post-delivery Template/repository change is D4, owned by M8.
type TicketTemplate string

// UpdateTicketRequest Manual refinement (issue #58): a genuine partial update. Every property is optional -- none are listed under `required` -- so a client can distinguish "this property was not part of the request" (leave unchanged) from "this property was sent as an empty string" (clear it, title excepted). See the `patch /api/tickets/{id}` operation above for the full rule, including why title cannot be cleared, and apps/galley/README.md, "Manual refinement fields," for the concurrent-edit (last-write-wins) rule. Trimmed of leading/trailing whitespace the same way CreateTicketRequest.title is; the maxLength values below apply after trimming and are counted in characters (code points), not bytes -- see apps/galley/README.md, "Tickets," "Title validation."
type UpdateTicketRequest struct {
	// Constraints Manual guidance: "State what must stay unchanged or remain out of scope." Same absent/empty/text rule as `goal`.
	Constraints *string `json:"constraints,omitempty"`

	// Context Manual guidance: "Supply relevant background, links, repositories, or examples." Same absent/empty/text rule as `goal`.
	Context *string `json:"context,omitempty"`

	// Goal Manual guidance: "What outcome do you want?" (docs/ticket-creation.md). Absent leaves the stored value unchanged; present as "" (or a value that trims to "") clears it; present with text trims and stores it.
	Goal *string `json:"goal,omitempty"`

	// Repository One Ticket repository reference (issue #59, D3), available on either Template. Same absent/empty/text rule as `goal`.
	Repository *string `json:"repository,omitempty"`

	// SuccessCriteria Manual guidance: "Describe observable conditions that demonstrate the outcome was achieved." Same absent/empty/text rule as `goal`. Agent-readiness validation of this field is M4's, not this slice's.
	SuccessCriteria *string `json:"successCriteria,omitempty"`

	// Template A Ticket's built-in Template (issue #59), chosen at capture (default Basic). Under the accepted D3 decision (docs/decisions/d3-agent-template-compatibility.md), a Template supplies presentation, required information, and a *default* completion condition only -- it never restricts which Agent or execution engine may be assigned (docs/ticket-creation.md, "Flexible ticket structure"). Changing a Ticket's Template after creation is out of scope for M2: post-delivery Template/repository change is D4, owned by M8.
	Template *TicketTemplate `json:"template,omitempty"`

	// Title If present, trimmed and validated exactly like CreateTicketRequest.title. A value that trims to empty is rejected with invalid_request rather than clearing the title -- every Ticket must keep one. Absent leaves the title unchanged.
	Title *string `json:"title,omitempty"`
}

// UsageCount `complete` and `estimated` mean for this figure what they mean for the cost in `RoundUsage`.
type UsageCount struct {
	Complete  bool `json:"complete"`
	Estimated bool `json:"estimated"`

	// Sum Null when no observation has a known value.
	Sum *int `json:"sum"`
}

// UsageObservedData Every key is required; null means unknown, never zero.
type UsageObservedData struct {
	ActiveMs *int                   `json:"activeMs"`
	Basis    UsageObservedDataBasis `json:"basis"`

	// CostUsd US dollars as a decimal string, so no binary float touches it.
	CostUsd     *string `json:"costUsd"`
	InputTokens *int    `json:"inputTokens"`
	Model       string  `json:"model"`

	// ObservationId The observation's identity, generated by the runner. Lowercase canonical form, not the nil UUID, and equal to the event's `idempotencyKey`.
	ObservationId string `json:"observationId"`
	OutputTokens  *int   `json:"outputTokens"`
	Provider      string `json:"provider"`

	// ProviderGenerationId Not unique and never identity; the join point for later enrichment (M9 #10).
	ProviderGenerationId *string `json:"providerGenerationId"`
}

// UsageObservedDataBasis defines model for UsageObservedData.Basis.
type UsageObservedDataBasis string

// CompleteGithubOAuthParams defines parameters for CompleteGithubOAuth.
type CompleteGithubOAuthParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Present when the provider itself reports failure (e.g. the user denied authorization).
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	// Archived True selects archived Tickets instead of unarchived Tickets.
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`

	// BadgeId Repeat to match any selected Badge; omit for all Tickets.
	BadgeId *[]string `form:"badgeId,omitempty" json:"badgeId,omitempty"`
}

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// RenameAgentJSONRequestBody defines body for RenameAgent for application/json ContentType.
type RenameAgentJSONRequestBody = RenameAgentRequest

// CreateBadgeJSONRequestBody defines body for CreateBadge for application/json ContentType.
type CreateBadgeJSONRequestBody = CreateBadgeRequest

// AdvanceDevClockJSONRequestBody defines body for AdvanceDevClock for application/json ContentType.
type AdvanceDevClockJSONRequestBody = AdvanceDevClockRequest

// CreateDiagnosticNoteJSONRequestBody defines body for CreateDiagnosticNote for application/json ContentType.
type CreateDiagnosticNoteJSONRequestBody = CreateDiagnosticNoteRequest

// RegisterRunnerJSONRequestBody defines body for RegisterRunner for application/json ContentType.
type RegisterRunnerJSONRequestBody = RegisterRunnerRequest

// AcknowledgeRoundCommandJSONRequestBody defines body for AcknowledgeRoundCommand for application/json ContentType.
type AcknowledgeRoundCommandJSONRequestBody = AcknowledgeRoundCommandRequest

// ReportRoundEventJSONRequestBody defines body for ReportRoundEvent for application/json ContentType.
type ReportRoundEventJSONRequestBody = RoundEventRequest

// CreateTicketJSONRequestBody defines body for CreateTicket for application/json ContentType.
type CreateTicketJSONRequestBody = CreateTicketRequest

// UpdateTicketJSONRequestBody defines body for UpdateTicket for application/json ContentType.
type UpdateTicketJSONRequestBody = UpdateTicketRequest

// AssignTicketJSONRequestBody defines body for AssignTicket for application/json ContentType.
type AssignTicketJSONRequestBody = AssignTicketRequest

// ReorderTicketJSONRequestBody defines body for ReorderTicket for application/json ContentType.
type ReorderTicketJSONRequestBody = ReorderTicketRequest

// ChangeTicketStatusJSONRequestBody defines body for ChangeTicketStatus for application/json ContentType.
type ChangeTicketStatusJSONRequestBody = ChangeTicketStatusRequest

// AsExecutionStartedData returns the union data inside the RoundEventRequest_Data as a ExecutionStartedData
func (t RoundEventRequest_Data) AsExecutionStartedData() (ExecutionStartedData, error) {
	var body ExecutionStartedData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExecutionStartedData overwrites any union data inside the RoundEventRequest_Data as the provided ExecutionStartedData
func (t *RoundEventRequest_Data) FromExecutionStartedData(v ExecutionStartedData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExecutionStartedData performs a merge with any union data inside the RoundEventRequest_Data, using the provided ExecutionStartedData
func (t *RoundEventRequest_Data) MergeExecutionStartedData(v ExecutionStartedData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProgressData returns the union data inside the RoundEventRequest_Data as a ProgressData
func (t RoundEventRequest_Data) AsProgressData() (ProgressData, error) {
	var body ProgressData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProgressData overwrites any union data inside the RoundEventRequest_Data as the provided ProgressData
func (t *RoundEventRequest_Data) FromProgressData(v ProgressData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProgressData performs a merge with any union data inside the RoundEventRequest_Data, using the provided ProgressData
func (t *RoundEventRequest_Data) MergeProgressData(v ProgressData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUsageObservedData returns the union data inside the RoundEventRequest_Data as a UsageObservedData
func (t RoundEventRequest_Data) AsUsageObservedData() (UsageObservedData, error) {
	var body UsageObservedData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUsageObservedData overwrites any union data inside the RoundEventRequest_Data as the provided UsageObservedData
func (t *RoundEventRequest_Data) FromUsageObservedData(v UsageObservedData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUsageObservedData performs a merge with any union data inside the RoundEventRequest_Data, using the provided UsageObservedData
func (t *RoundEventRequest_Data) MergeUsageObservedData(v UsageObservedData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeliveredData returns the union data inside the RoundEventRequest_Data as a DeliveredData
func (t RoundEventRequest_Data) AsDeliveredData() (DeliveredData, error) {
	var body DeliveredData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeliveredData overwrites any union data inside the RoundEventRequest_Data as the provided DeliveredData
func (t *RoundEventRequest_Data) FromDeliveredData(v DeliveredData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeliveredData performs a merge with any union data inside the RoundEventRequest_Data, using the provided DeliveredData
func (t *RoundEventRequest_Data) MergeDeliveredData(v DeliveredData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RoundEventRequest_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RoundEventRequest_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListAgents List the Owner's Agents
	// (GET /api/agents)
	ListAgents(w http.ResponseWriter, r *http.Request)
	// CreateAgent Create an Agent
	// (POST /api/agents)
	CreateAgent(w http.ResponseWriter, r *http.Request)
	// RenameAgent Rename an Agent
	// (PATCH /api/agents/{id})
	RenameAgent(w http.ResponseWriter, r *http.Request, id string)
	// CompleteGithubOAuth Complete GitHub OAuth sign-in
	// (GET /api/auth/github/callback)
	CompleteGithubOAuth(w http.ResponseWriter, r *http.Request, params CompleteGithubOAuthParams)
	// StartGithubOAuth Begin GitHub OAuth sign-in
	// (GET /api/auth/github/start)
	StartGithubOAuth(w http.ResponseWriter, r *http.Request)
	// ListBadges List the Owner's Badges
	// (GET /api/badges)
	ListBadges(w http.ResponseWriter, r *http.Request)
	// CreateBadge Create a reusable Badge
	// (POST /api/badges)
	CreateBadge(w http.ResponseWriter, r *http.Request)
	// AdvanceDevClock Advance Galley's clock
	// (POST /api/dev/clock/advance)
	AdvanceDevClock(w http.ResponseWriter, r *http.Request)
	// ListDiagnosticNotes List development diagnostic notes
	// (GET /api/dev/diagnostic-notes)
	ListDiagnosticNotes(w http.ResponseWriter, r *http.Request)
	// CreateDiagnosticNote Persist a development diagnostic note
	// (POST /api/dev/diagnostic-notes)
	CreateDiagnosticNote(w http.ResponseWriter, r *http.Request)
	// RevokeRunner Revoke the runner credential
	// (DELETE /api/runner-credential)
	RevokeRunner(w http.ResponseWriter, r *http.Request)
	// PairRunner Pair a runner
	// (POST /api/runner-credential)
	PairRunner(w http.ResponseWriter, r *http.Request)
	// GetRunnerHealth Runner health
	// (GET /api/runner-health)
	GetRunnerHealth(w http.ResponseWriter, r *http.Request)
	// ClaimWork Claim the next Round
	// (POST /api/runner/claims)
	ClaimWork(w http.ResponseWriter, r *http.Request)
	// RunnerHeartbeat Runner heartbeat
	// (POST /api/runner/heartbeat)
	RunnerHeartbeat(w http.ResponseWriter, r *http.Request)
	// RegisterRunner Register a runner
	// (POST /api/runner/register)
	RegisterRunner(w http.ResponseWriter, r *http.Request)
	// ListRoundCommands Pull a Round's unacknowledged commands
	// (GET /api/runner/rounds/{roundId}/commands)
	ListRoundCommands(w http.ResponseWriter, r *http.Request, roundId string)
	// AcknowledgeRoundCommand Acknowledge a pulled command
	// (POST /api/runner/rounds/{roundId}/commands/{commandId}/ack)
	AcknowledgeRoundCommand(w http.ResponseWriter, r *http.Request, roundId string, commandId string)
	// ReportRoundEvent Report an execution event for a Round
	// (POST /api/runner/rounds/{roundId}/events)
	ReportRoundEvent(w http.ResponseWriter, r *http.Request, roundId string)
	// SignOut Sign out
	// (DELETE /api/session)
	SignOut(w http.ResponseWriter, r *http.Request)
	// GetSession The signed-in Owner
	// (GET /api/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// GetStatus Application status
	// (GET /api/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// ListTickets List the signed-in Owner's Tickets
	// (GET /api/tickets)
	ListTickets(w http.ResponseWriter, r *http.Request, params ListTicketsParams)
	// CreateTicket Capture a Ticket from a title, optionally with details
	// (POST /api/tickets)
	CreateTicket(w http.ResponseWriter, r *http.Request)
	// GetTicket Get one Ticket by its identifier
	// (GET /api/tickets/{id})
	GetTicket(w http.ResponseWriter, r *http.Request, id string)
	// UpdateTicket Partially update a Ticket's manual refinement fields
	// (PATCH /api/tickets/{id})
	UpdateTicket(w http.ResponseWriter, r *http.Request, id string)
	// AcceptTicket Accept a Ticket's delivered work, completing it
	// (POST /api/tickets/{id}/accept)
	AcceptTicket(w http.ResponseWriter, r *http.Request, id string)
	// ArchiveTicket Archive a Ticket
	// (POST /api/tickets/{id}/archive)
	ArchiveTicket(w http.ResponseWriter, r *http.Request, id string)
	// UnassignTicket Clear a Ticket's Assignee
	// (DELETE /api/tickets/{id}/assignee)
	UnassignTicket(w http.ResponseWriter, r *http.Request, id string)
	// AssignTicket Assign the signed-in Owner or one of the Owner's Agents
	// (PUT /api/tickets/{id}/assignee)
	AssignTicket(w http.ResponseWriter, r *http.Request, id string)
	// DetachTicketBadge Remove a Badge from a Ticket
	// (DELETE /api/tickets/{id}/badges/{badgeId})
	DetachTicketBadge(w http.ResponseWriter, r *http.Request, id string, badgeId string)
	// AttachTicketBadge Attach an existing Badge to a Ticket
	// (PUT /api/tickets/{id}/badges/{badgeId})
	AttachTicketBadge(w http.ResponseWriter, r *http.Request, id string, badgeId string)
	// ReorderTicket Move a Ticket before or after another in the Owner's priority order
	// (POST /api/tickets/{id}/position)
	ReorderTicket(w http.ResponseWriter, r *http.Request, id string)
	// RestoreTicket Restore an archived Ticket
	// (POST /api/tickets/{id}/restore)
	RestoreTicket(w http.ResponseWriter, r *http.Request, id string)
	// RequestTicketRework Return an In Review Ticket to Ready for another Round
	// (POST /api/tickets/{id}/rework)
	RequestTicketRework(w http.ResponseWriter, r *http.Request, id string)
	// ListTicketRounds List a Ticket's Rounds
	// (GET /api/tickets/{id}/rounds)
	ListTicketRounds(w http.ResponseWriter, r *http.Request, id string)
	// ChangeTicketStatus Change a Ticket's Status
	// (POST /api/tickets/{id}/status)
	ChangeTicketStatus(w http.ResponseWriter, r *http.Request, id string)
	// RequestTicketStop Request Stop of the Ticket's open Round
	// (POST /api/tickets/{id}/stop)
	RequestTicketStop(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RenameAgent operation middleware
func (siw *ServerInterfaceWrapper) RenameAgent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RenameAgent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteGithubOAuth operation middleware
func (siw *ServerInterfaceWrapper) CompleteGithubOAuth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteGithubOAuthParams

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", r.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteGithubOAuth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartGithubOAuth operation middleware
func (siw *ServerInterfaceWrapper) StartGithubOAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartGithubOAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBadges operation middleware
func (siw *ServerInterfaceWrapper) ListBadges(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBadges(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBadge operation middleware
func (siw *ServerInterfaceWrapper) CreateBadge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBadge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdvanceDevClock operation middleware
func (siw *ServerInterfaceWrapper) AdvanceDevClock(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdvanceDevClock(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDiagnosticNotes operation middleware
func (siw *ServerInterfaceWrapper) ListDiagnosticNotes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDiagnosticNotes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDiagnosticNote operation middleware
func (siw *ServerInterfaceWrapper) CreateDiagnosticNote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDiagnosticNote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeRunner operation middleware
func (siw *ServerInterfaceWrapper) RevokeRunner(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeRunner(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PairRunner operation middleware
func (siw *ServerInterfaceWrapper) PairRunner(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PairRunner(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunnerHealth operation middleware
func (siw *ServerInterfaceWrapper) GetRunnerHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunnerHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClaimWork operation middleware
func (siw *ServerInterfaceWrapper) ClaimWork(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClaimWork(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunnerHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) RunnerHeartbeat(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerHeartbeat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterRunner operation middleware
func (siw *ServerInterfaceWrapper) RegisterRunner(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterRunner(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRoundCommands operation middleware
func (siw *ServerInterfaceWrapper) ListRoundCommands(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roundId" -------------
	var roundId string

	err = runtime.BindStyledParameterWithOptions("simple", "roundId", r.PathValue("roundId"), &roundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roundId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRoundCommands(w, r, roundId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcknowledgeRoundCommand operation middleware
func (siw *ServerInterfaceWrapper) AcknowledgeRoundCommand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roundId" -------------
	var roundId string

	err = runtime.BindStyledParameterWithOptions("simple", "roundId", r.PathValue("roundId"), &roundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roundId", Err: err})
		return
	}

	// ------------- Path parameter "commandId" -------------
	var commandId string

	err = runtime.BindStyledParameterWithOptions("simple", "commandId", r.PathValue("commandId"), &commandId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commandId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcknowledgeRoundCommand(w, r, roundId, commandId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReportRoundEvent operation middleware
func (siw *ServerInterfaceWrapper) ReportRoundEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "roundId" -------------
	var roundId string

	err = runtime.BindStyledParameterWithOptions("simple", "roundId", r.PathValue("roundId"), &roundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roundId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReportRoundEvent(w, r, roundId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignOut(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTickets operation middleware
func (siw *ServerInterfaceWrapper) ListTickets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "badgeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "badgeId", r.URL.Query(), &params.BadgeId, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "badgeId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "badgeId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTickets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateTicket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTicket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicket operation middleware
func (siw *ServerInterfaceWrapper) GetTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTicket operation middleware
func (siw *ServerInterfaceWrapper) UpdateTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptTicket operation middleware
func (siw *ServerInterfaceWrapper) AcceptTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveTicket operation middleware
func (siw *ServerInterfaceWrapper) ArchiveTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnassignTicket operation middleware
func (siw *ServerInterfaceWrapper) UnassignTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnassignTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignTicket operation middleware
func (siw *ServerInterfaceWrapper) AssignTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DetachTicketBadge operation middleware
func (siw *ServerInterfaceWrapper) DetachTicketBadge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "badgeId" -------------
	var badgeId string

	err = runtime.BindStyledParameterWithOptions("simple", "badgeId", r.PathValue("badgeId"), &badgeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "badgeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DetachTicketBadge(w, r, id, badgeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachTicketBadge operation middleware
func (siw *ServerInterfaceWrapper) AttachTicketBadge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "badgeId" -------------
	var badgeId string

	err = runtime.BindStyledParameterWithOptions("simple", "badgeId", r.PathValue("badgeId"), &badgeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "badgeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachTicketBadge(w, r, id, badgeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReorderTicket operation middleware
func (siw *ServerInterfaceWrapper) ReorderTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReorderTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreTicket operation middleware
func (siw *ServerInterfaceWrapper) RestoreTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestTicketRework operation middleware
func (siw *ServerInterfaceWrapper) RequestTicketRework(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestTicketRework(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTicketRounds operation middleware
func (siw *ServerInterfaceWrapper) ListTicketRounds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTicketRounds(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeTicketStatus operation middleware
func (siw *ServerInterfaceWrapper) ChangeTicketStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeTicketStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestTicketStop operation middleware
func (siw *ServerInterfaceWrapper) RequestTicketStop(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestTicketStop(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/dev/diagnostic-notes", wrapper.ListDiagnosticNotes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/dev/diagnostic-notes", wrapper.CreateDiagnosticNote)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/auth/github/start", wrapper.StartGithubOAuth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/auth/github/callback", wrapper.CompleteGithubOAuth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/tickets", wrapper.ListTickets)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets", wrapper.CreateTicket)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/tickets/{id}", wrapper.GetTicket)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/tickets/{id}", wrapper.UpdateTicket)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets/{id}/status", wrapper.ChangeTicketStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets/{id}/accept", wrapper.AcceptTicket)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets/{id}/rework", wrapper.RequestTicketRework)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets/{id}/stop", wrapper.RequestTicketStop)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/tickets/{id}/assignee", wrapper.UnassignTicket)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/tickets/{id}/assignee", wrapper.AssignTicket)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/badges", wrapper.ListBadges)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/badges", wrapper.CreateBadge)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agents", wrapper.ListAgents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/agents", wrapper.CreateAgent)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/agents/{id}", wrapper.RenameAgent)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/tickets/{id}/badges/{badgeId}", wrapper.DetachTicketBadge)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/tickets/{id}/badges/{badgeId}", wrapper.AttachTicketBadge)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets/{id}/archive", wrapper.ArchiveTicket)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets/{id}/restore", wrapper.RestoreTicket)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/tickets/{id}/position", wrapper.ReorderTicket)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/tickets/{id}/rounds", wrapper.ListTicketRounds)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/session", wrapper.SignOut)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/session", wrapper.GetSession)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/runner-credential", wrapper.RevokeRunner)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/runner-credential", wrapper.PairRunner)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/runner-health", wrapper.GetRunnerHealth)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/runner/register", wrapper.RegisterRunner)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/runner/heartbeat", wrapper.RunnerHeartbeat)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/runner/claims", wrapper.ClaimWork)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/runner/rounds/{roundId}/events", wrapper.ReportRoundEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/runner/rounds/{roundId}/commands", wrapper.ListRoundCommands)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/runner/rounds/{roundId}/commands/{commandId}/ack", wrapper.AcknowledgeRoundCommand)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/dev/clock/advance", wrapper.AdvanceDevClock)

	return m
}
