//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
)

// Defines values for StatusResponseApplication.
const (
	Galley StatusResponseApplication = "galley"
)

// Valid indicates whether the value is a known member of the StatusResponseApplication enum.
func (e StatusResponseApplication) Valid() bool {
	switch e {
	case Galley:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseEnvironment.
const (
	Development StatusResponseEnvironment = "development"
	Production  StatusResponseEnvironment = "production"
)

// Valid indicates whether the value is a known member of the StatusResponseEnvironment enum.
func (e StatusResponseEnvironment) Valid() bool {
	switch e {
	case Development:
		return true
	case Production:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseStatus.
const (
	Ok StatusResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// ErrorBody The shared JSON error shape used by every Galley error response.
type ErrorBody struct {
	Error ErrorDetail `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Short, stable, snake_case identifier (e.g. "not_found").
	Code string `json:"code"`

	// Message Human-readable, non-secret explanation.
	Message string `json:"message"`
}

// StatusResponse The fixed GET /api/status payload.
type StatusResponse struct {
	Application StatusResponseApplication `json:"application"`
	Environment StatusResponseEnvironment `json:"environment"`

	// StartedAt RFC3339 UTC timestamp, captured once at process start.
	StartedAt string               `json:"startedAt"`
	Status    StatusResponseStatus `json:"status"`

	// Version Galley's configured version string (GALLEY_VERSION).
	Version string `json:"version"`
}

// StatusResponseApplication defines model for StatusResponse.Application.
type StatusResponseApplication string

// StatusResponseEnvironment defines model for StatusResponse.Environment.
type StatusResponseEnvironment string

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetStatus Application status
	// (GET /api/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/status", wrapper.GetStatus)

	return m
}
